wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.11.6
    cli_version: 0.15.11
    framework: huggingface
    huggingface_version: 4.56.0
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1759783722.445059
    t:
      1:
      - 1
      - 5
      - 11
      - 41
      - 49
      - 53
      - 55
      2:
      - 1
      - 5
      - 11
      - 41
      - 49
      - 53
      - 55
      3:
      - 13
      - 23
      4: 3.11.6
      5: 0.15.11
      6: 4.56.0
      8:
      - 4
      - 5
      13: darwin-arm64
datasets:
  desc: null
  value:
  - ../datasets/RatcliffLab-model
  - ../datasets/RatcliffLab-analyze
sam_model:
  desc: null
  value: facebook/sam-vit-base
batch_size:
  desc: null
  value: 4
num_epochs:
  desc: null
  value: 50
learning_rate:
  desc: null
  value: 0.0001
weight_decay:
  desc: null
  value: 0.1
patience:
  desc: null
  value: 10
min_delta:
  desc: null
  value: 0.0001
finetune_vision:
  desc: null
  value: true
